version: '3'
services:
 mysqldb:
  container_name: form-database
  image: mysql:8.0.1
  environment:
   MYSQL_DATABASE: 'dev_db'
   MYSQL_USER: 'dev_user'
   MYSQL_PASSWORD: 'dev_pass'
   MYSQL_ROOT_PASSWORD: 'root_pass'
  ports:
   - "3306:3306"
  volumes:
   - "./data-mysql:/var/lib/mysql"

 phpmyadmin:
    container_name: form-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    links:
      - mysqldb:db